/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Validacoes;
import file.Ficheiro;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import model.TabelaTokens;
import model.Token;
/**
 *
 * @author user
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form IDE
     */
    private String[] colunas = {"Token", "Classe", "Linha"};
        
    public MainFrame() {        
        setTitle("COMPILADOR LÉXICO");
        initComponents();        
        editor.setBorder(new Rows());
        linha = new ArrayList<>();
        model_table = new TabelaTokens(linha, colunas);
        TableCellRenderer renderer = new EvenOddRenderer();
        jTable1.setDefaultRenderer(Object.class, renderer);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        open_file_btn = new javax.swing.JButton();
        run_btn = new javax.swing.JButton();
        create_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        editor = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setLayout(new java.awt.BorderLayout(2, 2));

        jPanel2.setBackground(new java.awt.Color(40, 42, 54));

        jToolBar1.setBackground(new java.awt.Color(40, 42, 54));
        jToolBar1.setRollover(true);

        open_file_btn.setBackground(new java.awt.Color(102, 107, 139));
        open_file_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-abrir-arquivo-sob-o-cursor-30.png"))); // NOI18N
        open_file_btn.setToolTipText("Abrir Ficheiro");
        open_file_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(0, null, new java.awt.Color(0, 204, 204), null, null));
        open_file_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        open_file_btn.setFocusable(false);
        open_file_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        open_file_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        open_file_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_file_btnActionPerformed(evt);
            }
        });
        jToolBar1.add(open_file_btn);

        run_btn.setBackground(new java.awt.Color(102, 107, 139));
        run_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-powershell-30.png"))); // NOI18N
        run_btn.setToolTipText("Executar");
        run_btn.setAlignmentX(0.5F);
        run_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(0, null, new java.awt.Color(0, 204, 204), null, null));
        run_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        run_btn.setFocusable(false);
        run_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        run_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        run_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                run_btnActionPerformed(evt);
            }
        });
        jToolBar1.add(run_btn);

        create_btn.setBackground(new java.awt.Color(102, 107, 139));
        create_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-novo-por-cópia-30.png"))); // NOI18N
        create_btn.setToolTipText("Novo Ficheiro");
        create_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(0, null, new java.awt.Color(0, 204, 204), null, null));
        create_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        create_btn.setFocusable(false);
        create_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        create_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        create_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_btnActionPerformed(evt);
            }
        });
        jToolBar1.add(create_btn);

        save_btn.setBackground(new java.awt.Color(102, 107, 139));
        save_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-salvar-30.png"))); // NOI18N
        save_btn.setToolTipText("Guardar");
        save_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(0, null, new java.awt.Color(0, 204, 204), null, null));
        save_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save_btn.setFocusable(false);
        save_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        save_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        jToolBar1.add(save_btn);

        clear_btn.setBackground(new java.awt.Color(102, 107, 139));
        clear_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-vassoura-30.png"))); // NOI18N
        clear_btn.setToolTipText("Limpar Editor");
        clear_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(0, null, new java.awt.Color(0, 204, 204), null, null));
        clear_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear_btn.setFocusable(false);
        clear_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clear_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        jToolBar1.add(clear_btn);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        container.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(40, 42, 54));

        jTree1.setBackground(new java.awt.Color(40, 42, 54));
        jScrollPane3.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        );

        container.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jScrollPane1.setBackground(new java.awt.Color(68, 71, 90));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setToolTipText("");
        jScrollPane1.setAutoscrolls(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Token", "Lexema", "Padrao", "Classe", "Linha"
            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
        );

        container.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        editor.setBackground(new java.awt.Color(68, 71, 90));
        editor.setColumns(20);
        editor.setFont(new java.awt.Font("Lucida Console", 0, 17)); // NOI18N
        editor.setForeground(new java.awt.Color(248, 248, 242));
        editor.setRows(5);
        editor.setCaretColor(new java.awt.Color(139, 233, 253));
        editor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane4.setViewportView(editor);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        );

        container.add(jPanel7, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(98, 114, 164));
        jMenuBar1.setForeground(new java.awt.Color(248, 248, 242));

        jMenu1.setText("Ficheiro");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void open_file_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_file_btnActionPerformed
        // TODO add your handling code here:
        openFile();
    }//GEN-LAST:event_open_file_btnActionPerformed

    private void run_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_run_btnActionPerformed
        // TODO add your handling code here:
        if (!editor.getText().isEmpty()) {
            jTable1.removeAll();
            model_table.removeall();
            array();
            jTable1.setModel(model_table);
            jTable1.setVisible(true);
        } else {
        }
    }//GEN-LAST:event_run_btnActionPerformed

    private void create_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_btnActionPerformed
        // TODO add your handling code here:
        String nome = JOptionPane.showInputDialog("Nome do projeto");
        Ficheiro.criar(nome);
    }//GEN-LAST:event_create_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
        editor.setText("");
        model_table.removeall();
        jTable1.removeAll();
        jTable1.setModel(model_table);
        jTable1.setVisible(false);
    }//GEN-LAST:event_clear_btnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_save_btnActionPerformed
    
    public void array() {

        String texto = editor.getText();
        int posicao = 0;
        model_table.removeall();
        if (texto.length() > 0) {
            String[] textosplit;
            textosplit = texto.split("\n");

            for (int i = 0; i < textosplit.length; i++) {
                String textoposix = textosplit[i];
                String[] lista = textoposix.split(" ");

                for (int k = 0; k < lista.length; k++) {
                    posicao = posicao + lista[k].length() + 1;
                    Token token = new Token(validar(lista[k]), lista[k], i + 1, posicao);
                    if(!token.getToken().equals(""))
                    model_table.addlinha(token);

                }
            }
        } else {
            jTable1.removeAll();
            jTable1.clearSelection();
        }

    }
    
    public String validar(String lexema) {
        return classificar.validar(lexema);
    }
    
    class EvenOddRenderer implements TableCellRenderer {

        public final DefaultTableCellRenderer DEFAULT_RENDERER = new DefaultTableCellRenderer();
        Token token;

        public List<Token> list;

        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            Component renderer = DEFAULT_RENDERER.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            Color foreground, background;
            this.list = model_table.getLinhas();

            if (isSelected) {
                foreground = Color.WHITE;
                background = new Color(153, 153, 153);
            } else {
                if (this.list.get(row).getClasse().equals("ERRO")) {
                    foreground = Color.BLACK;
                    background = new Color(255, 184, 108);
                } else {
                    foreground = Color.BLACK;
                    background = new Color(255, 255, 255);
                }
            }
            renderer.setForeground(foreground);
            renderer.setBackground(background);
            return renderer;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    private void openFile() {
        JFileChooser jFile = new JFileChooser(System.getProperty("user.dir"));

        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.jeans", "jeans");

        jFile.addChoosableFileFilter(filter);
        jFile.setAcceptAllFileFilterUsed(false);

        jFile.setDialogType(JFileChooser.OPEN_DIALOG);

        int result = jFile.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jFile.getSelectedFile();
            String path = selectedFile.getAbsolutePath();

        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("CANCELED");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear_btn;
    private javax.swing.JPanel container;
    private javax.swing.JButton create_btn;
    private javax.swing.JTextArea editor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton open_file_btn;
    private javax.swing.JButton run_btn;
    private javax.swing.JButton save_btn;
    // End of variables declaration//GEN-END:variables

    private ArrayList<Token> linha;
    private TabelaTokens model_table;
    private Validacoes classificar;
}
